// Generated by CoffeeScript 1.8.0
(function() {
  var assert, should, webdriver;

  webdriver = require('selenium-webdriver');

  assert = require('assert');

  should = require('should');

  describe('Peter plays the first level', function() {
    var driver, instructions, target_zoom;
    driver = new webdriver.Builder().withCapabilities(webdriver.Capabilities.chrome()).build();
    driver.get('file:///home/dough/workspace/JSFractalGame/src/exampleUsage.html');
    driver.findElement(webdriver.By.id('target-fractal'));
    driver.findElement(webdriver.By.id('target-canvas'));
    target_zoom = driver.findElement(webdriver.By.id('target-zoom'));
    (target_zoom === null).should.not.be.ok;
    target_zoom.text.should.containEql('x');
    driver.findElement(webdriver.By.id('fractal-game'));
    driver.findElement(webdriver.By.id('fractal-canvas'));
    instructions = driver.findElement(webdriver.By.id('fractal-game-instructions'));
    (instructions === null).should.not.be.ok;
    instructions.text.should.containEql('Click to zoom');
    return driver.quit();
  });

}).call(this);
