// Generated by CoffeeScript 1.8.0
(function() {
  var fractal_game, fractal_game_view, fractal_manager;

  window.fractal_api_url = "http://localhost:8000/api/";

  fractal_game = new window.FractalGame({
    width: 400,
    height: 285
  }, MANDELBROT_CANVAS_SIZE);

  fractal_game_view = new window.FractalGameView({
    model: fractal_game
  });

  fractal_manager = new window.FractalManager(MANDELBROT_CANVAS_SIZE, 400, 285);

  describe('FractalGame', function() {
    describe('startLevel(level: int)', function() {
      it('should set the current zoom level to 1', function() {
        fractal_game.startLevel(1);
        return fractal_game.get('zoom').should.be.exactly(1);
      });
      it('should set the current game`s level', function() {
        fractal_game.startLevel(2);
        return fractal_game.get('level').should.be.exactly(2);
      });
      it('should set the maximum zoom for this game`s level', function() {
        fractal_game.startLevel(1);
        return fractal_game.get('max_zoom').should.be.exactly(4);
      });
      return it('should set the clicks left counter to the level + 2', function() {
        fractal_game.startGame();
        fractal_game.startLevel(1);
        fractal_game.clicks_remaining.should.be.exactly(3);
        fractal_game.startLevel(3);
        fractal_game.clicks_remaining.should.be.exactly(5);
        fractal_game.startLevel(2);
        return fractal_game.clicks_remaining.should.be.exactly(4);
      });
    });
    describe('startGame()', function() {
      it('should set the game`s level to 1', function() {
        fractal_game.startGame();
        return fractal_game.get('level').should.be.exactly(1);
      });
      return it('should start at level 1', function() {
        fractal_game.startGame();
        fractal_game.get('zoom').should.be.exactly(1);
        return fractal_game.get('max_zoom').should.be.exactly(4);
      });
    });
    describe('generateRoute(level: int, success_function: ->, failure_function: ->)', function() {
      it('should reject unreasonable levels', function() {
        var error, route;
        error = 0;
        try {
          route = fractal_game(-1);
        } catch (_error) {
          error = _error;
        }
        error.should.not.eql(0);
        error = 0;
        try {
          route = fractal_game(50);
        } catch (_error) {
          error = _error;
        }
        return error.should.not.eql(0);
      });
      it('should return an array at level 1 with a route that has an x/y value, ex: [{x:0,y:0}]', function() {
        return fractal_game.generateRoute(1, function(route) {
          route.length.should.eql(1);
          return (route[0].x === null || route[0].y === null).should.not.be["true"];
        });
      });
      return it('should return an array at level 2 with two routes that are each 5 characters long', function() {
        return fractal_game.generateRoute(2, function(route) {
          route.length.should.eql(2);
          (route[0].x === null || route[0].y === null).should.not.be["true"];
          return (route[1].x === null || route[1].y === null).should.not.be["true"];
        });
      });
    });
    return describe('back()', function() {
      it('should zoom the canvas out zoom_multiplier times', function() {
        fractal_game.startGame();
        fractal_game.startLevel(2);
        fractal_game.zoomIn({
          x: 1,
          y: 1
        });
        fractal_game.back();
        return fractal_game.get('zoom').should.be.exactly(1);
      });
      it('should not change anything if already at the top-most level', function() {
        var clicks_remaining;
        fractal_game.startGame();
        clicks_remaining = fractal_game.clicks_remaining;
        fractal_game.back();
        fractal_game.get('zoom').should.be.exactly(1);
        return fractal_game.clicks_remaining.should.be.exactly(clicks_remaining);
      });
      it('should decrement the clicks remaining counter', function() {
        var local_fractal_game;
        local_fractal_game = new window.FractalGame({
          width: 400,
          height: 285
        }, MANDELBROT_CANVAS_SIZE);
        local_fractal_game.startGame();
        local_fractal_game.startLevel(2);
        return setTimeout((function(_this) {
          return function() {
            var clicks_remaining;
            local_fractal_game.zoomIn({
              x: 1,
              y: 1
            });
            clicks_remaining = fractal_game.clicks_remaining;
            local_fractal_game.back();
            return local_fractal_game.clicks_remaining.should.be.exactly(clicks_remaining - 1);
          };
        })(this), 100);
      });
      it('should not change anything if there are no clicks remaining', function() {
        var local_fractal_game;
        local_fractal_game = new window.FractalGame({
          width: 400,
          height: 285
        }, MANDELBROT_CANVAS_SIZE);
        local_fractal_game.startGame();
        return setTimeout((function(_this) {
          return function() {
            while (local_fractal_game.clicks_remaining > 0) {
              local_fractal_game.zoomIn({
                x: 1,
                y: 1
              });
            }
            return setTimeout(function() {
              var zoom;
              zoom = local_fractal_game.get('zoom');
              local_fractal_game.back();
              local_fractal_game.clicks_remaining.should.be.exactly(0);
              return local_fractal_game.get('zoom').should.be.exactly(zoom);
            }, 100);
          };
        })(this), 200);
      });
      it('shouldn`t prevent the user from reaching the correct route', function() {
        var local_fractal_game;
        local_fractal_game = new window.FractalGame({
          width: 400,
          height: 285
        }, MANDELBROT_CANVAS_SIZE);
        local_fractal_game.startGame();
        return setTimeout((function(_this) {
          return function() {
            local_fractal_game.zoomIn({
              x: 0,
              y: 0
            });
            local_fractal_game.back();
            local_fractal_game.zoomIn(local_fractal_game.target_route[0]);
            return local_fractal_game.may_play_next_level.should.be["true"];
          };
        })(this), 200);
      });
      return it('should end the level if the clicks remaining counter decrements to zero', function() {
        var local_fractal_game;
        local_fractal_game = new window.FractalGame({
          width: 400,
          height: 285
        }, MANDELBROT_CANVAS_SIZE);
        local_fractal_game.startGame();
        local_fractal_game.startLevel(2);
        return setTimeout((function(_this) {
          return function() {
            local_fractal_game.zoomIn({
              x: 1,
              y: 1
            });
            local_fractal_game.zoomIn({
              x: 1,
              y: 1
            });
            local_fractal_game.zoomIn({
              x: 1,
              y: 1
            });
            local_fractal_game.back();
            local_fractal_game.level_over.should.be["true"];
            return local_fractal_game.may_play_next_level.should.be["false"];
          };
        })(this), 200);
      });
    });
  });

  describe('FractalManager', function() {
    describe('FractalManager(canvas_size: {width: int, height: int}, top_left_default: {x: int, y: int}, bottom_right_default: {x: int, y: int})', function() {
      it('should set the initial top left and bottom right values', function() {
        fractal_manager.get('top_left').should.eql({
          x: -2.5,
          y: 1.25
        });
        return fractal_manager.get('bottom_right').should.eql({
          x: 1,
          y: -1.25
        });
      });
      return it('should calculate the width and height of the entire canvas', function() {
        fractal_manager.get('entire_width').should.eql(3.5);
        return fractal_manager.get('entire_height').should.eql(2.5);
      });
    });
    describe('resetCanvas()', function() {
      return it('should set the top left and bottom right coordinates back to their default values', function() {
        fractal_manager.setCanvas({
          x: 0.5,
          y: 0.5
        }, 4);
        fractal_manager.resetCanvas();
        fractal_manager.get('bottom_right').should.eql(fractal_manager.get('default_bottom_right'));
        return fractal_manager.get('top_left').should.eql(fractal_manager.get('default_top_left'));
      });
    });
    describe('setCanvas(target_section: {x: int, y: int}, zoom: int, old_zoom: int)', function() {
      it('should update the fractal`s top_left coordinate', function() {
        fractal_manager.setCanvas({
          x: 1,
          y: 1
        }, 4);
        fractal_manager.get('top_left').should.eql({
          x: -1.625,
          y: 0.625
        });
        fractal_manager.resetCanvas();
        fractal_manager.setCanvas({
          x: 3,
          y: 0
        }, 4);
        return fractal_manager.get('top_left').should.eql({
          x: 0.125,
          y: 1.25
        });
      });
      return it('should calculate and update the fractal`s bottom_right coordinate', function() {
        fractal_manager.resetCanvas();
        fractal_manager.setCanvas({
          x: 1,
          y: 1
        }, 4);
        fractal_manager.get('bottom_right').should.eql({
          x: -0.75,
          y: 0
        });
        fractal_manager.setCanvas({
          x: 1,
          y: 1
        }, 16);
        return fractal_manager.get('bottom_right').should.eql({
          x: -1.1875,
          y: 0.3125
        });
      });
    });
    return describe('previousCanvas()', function() {
      it('should return the default canvas when there`s no history left to undo', function() {
        fractal_manager.resetCanvas();
        fractal_manager.previousCanvas();
        fractal_manager.get('top_left').should.eql(fractal_manager.get('default_top_left'));
        return fractal_manager.get('bottom_right').should.eql(fractal_manager.get('default_bottom_right'));
      });
      return it('should go back one canvas in history', function() {
        fractal_manager.resetCanvas();
        fractal_manager.setCanvas({
          x: 1,
          y: 1
        }, 4);
        fractal_manager.previousCanvas();
        fractal_manager.get('top_left').should.eql(fractal_manager.get('default_top_left'));
        fractal_manager.get('bottom_right').should.eql(fractal_manager.get('default_bottom_right'));
        fractal_manager.setCanvas({
          x: 1,
          y: 1
        }, 4);
        fractal_manager.setCanvas({
          x: 2,
          y: 2
        }, 16);
        fractal_manager.previousCanvas();
        fractal_manager.get('top_left').should.eql({
          x: -1.625,
          y: 0.625
        });
        fractal_manager.get('bottom_right').should.eql({
          x: -0.75,
          y: 0
        });
        fractal_manager.previousCanvas();
        fractal_manager.get('top_left').should.eql(fractal_manager.get('default_top_left'));
        return fractal_manager.get('bottom_right').should.eql(fractal_manager.get('default_bottom_right'));
      });
    });
  });

}).call(this);
