// Generated by CoffeeScript 1.8.0
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.ActiveFractal = (function(_super) {
    __extends(_Class, _super);

    function _Class() {
      this.startGame = __bind(this.startGame, this);
      this.startLevel = __bind(this.startLevel, this);
      return _Class.__super__.constructor.apply(this, arguments);
    }

    _Class.prototype.defaults = {
      zoom: 1,
      coordinates: [0, 0],
      level: 1,
      max_zoom: 2,
      zoom_multiplier: 4
    };

    _Class.prototype.startLevel = function(this_level) {
      this.set('level', this_level);
      this.set('zoom', 1);
      return this.set('max_zoom', Math.pow(this.get('zoom_multiplier'), this_level));
    };

    _Class.prototype.startGame = function() {
      return this.startLevel(1);
    };

    return _Class;

  })(Backbone.Model);

  window.ActiveFractalView = (function(_super) {
    __extends(_Class, _super);

    _Class.prototype.template = _.template("<div id='instructions'> Click to zoom in. Try to zoom in to the exact location of the fractal on the left. </div> <div class='canvas-header'> Current Level: <%= level %> clicks deep Zoom at target location: x<%= max_zoom %> </div> <div id='active-canvas'> <%= fractal %> <div id='active-zoom' class='zoom'><%= zoom %>x</div> </div>");

    function _Class(options) {
      if (options == null) {
        options = {};
      }
      this.render = __bind(this.render, this);
      this.model = options.model, this.classname = options.classname;
      $(document).on("ready", (function(_this) {
        return function() {
          _this.$el = $('#active-fractal');
          return _this.render();
        };
      })(this));
    }

    _Class.prototype.initialize = function() {
      return this.model.on('change', this.render, this);
    };

    _Class.prototype.render_fractal = function() {
      return 'dud';
    };

    _Class.prototype.render = function() {
      return this.$el.html(this.template({
        'zoom': this.model.get('zoom'),
        'level': this.model.get('level'),
        'max_zoom': this.model.get('max_zoom'),
        'fractal': this.render_fractal()
      }));
    };

    return _Class;

  })(Backbone.View);

}).call(this);
