// Generated by CoffeeScript 1.8.0
(function() {
  var active, activeView, target, targetView;

  target = new window.TargetFractal(MANDELBROT_CANVAS_SIZE);

  targetView = new window.TargetFractalView({
    model: target
  });

  active = new window.ActiveFractal(MANDELBROT_CANVAS_SIZE);

  activeView = new window.ActiveFractalView({
    model: active
  });

}).call(this);
