// Generated by CoffeeScript 1.8.0
(function() {
  var target, targetView;

  target = new window.TargetFractal();

  targetView = new window.TargetFractalView({
    model: target
  });

}).call(this);
