// Generated by CoffeeScript 1.8.0
(function() {
  window.bad_routes = {
    0: {
      0: false,
      1: {
        0: {},
        1: {},
        2: {},
        3: {}
      },
      2: {
        0: {},
        1: {},
        2: {},
        3: {}
      },
      3: false
    },
    1: {
      0: false,
      1: {
        0: {},
        1: {},
        2: {},
        3: {}
      },
      2: {
        0: {},
        1: {},
        2: {},
        3: {}
      },
      3: false
    },
    2: {
      0: {},
      1: {},
      2: {},
      3: {}
    },
    3: {
      0: {},
      1: {},
      2: {},
      3: {}
    },
    max_depth: 1
  };

}).call(this);
