// Generated by CoffeeScript 1.8.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.FractalManager = (function(_super) {
    __extends(_Class, _super);

    function _Class() {
      return _Class.__super__.constructor.apply(this, arguments);
    }

    _Class.prototype.defaults = {
      top_left: {
        x: 0,
        y: 1
      },
      bottom_right: {
        x: 1,
        y: 0
      }
    };

    _Class.prototype.setCanvas = function(new_top_left, zoom) {
      this.set('top_left', new_top_left);
      return this.set('bottom_right', {
        x: this.get('top_left').x + 1 / zoom,
        y: this.get('top_left').y - 1 / zoom
      });
    };

    _Class.prototype.renderCanvas = function() {
      return console.log('not yet');
    };

    return _Class;

  })(Backbone.Model);

}).call(this);
