// Generated by CoffeeScript 1.8.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  window.FractalManager = (function(_super) {
    __extends(_Class, _super);

    _Class.prototype.top_left = {
      x: 0,
      y: 0
    };

    _Class.prototype.bottom_right = {
      x: 0,
      y: 0
    };

    _Class.prototype.default_top_left = {
      x: 0,
      y: 0
    };

    _Class.prototype.default_bottom_right = {
      x: 0,
      y: 0
    };

    _Class.prototype.entire_width = 0;

    _Class.prototype.entire_height = 0;

    _Class.prototype.canvas = 0;

    _Class.prototype.color_picker = pickColorHSV1;

    _Class.prototype.fractal_algorithm = mandelbrotAlgorithm;

    _Class.prototype.fractal_range = 0;

    function _Class(canvas_size) {
      Backbone.Model.apply(this);
      this.set('default_top_left', canvas_size.top_left);
      this.set('default_bottom_right', canvas_size.bottom_right);
      this.set('top_left', canvas_size.top_left);
      this.set('bottom_right', canvas_size.bottom_right);
      this.set('entire_width', canvas_size.bottom_right.x - canvas_size.top_left.x);
      this.set('entire_height', canvas_size.top_left.y - canvas_size.bottom_right.y);
    }

    _Class.prototype.setCanvas = function(new_top_left, zoom) {
      this.set('top_left', new_top_left);
      return this.set('bottom_right', {
        x: this.get('top_left').x + this.get('entire_width') / zoom,
        y: this.get('top_left').y - this.get('entire_height') / zoom
      });
    };

    _Class.prototype.resetCanvas = function() {
      this.set('top_left', this.get('default_top_left'));
      return this.set('bottom_right', this.get('default_bottom_right'));
    };

    return _Class;

  })(Backbone.Model);

  window.FractalManagerView = (function(_super) {
    __extends(_Class, _super);

    _Class.prototype.defaults = {
      canvas_selector: 0
    };

    function _Class(model, canvas_selector) {
      this.model = model;
      this.canvas_selector = canvas_selector;
      this.render = __bind(this.render, this);
    }

    _Class.prototype.render = function() {
      return draw($(this.canvas_selector)[0], this.model.get('top_left'), this.model.get('bottom_right'), this.model.color_picker, this.model.fractal_algorithm);
    };

    return _Class;

  })(Backbone.View);

}).call(this);
