// Generated by CoffeeScript 1.8.0
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.TargetFractal = (function(_super) {
    __extends(_Class, _super);

    function _Class() {
      this.zoomIn = __bind(this.zoomIn, this);
      return _Class.__super__.constructor.apply(this, arguments);
    }

    _Class.prototype.defaults = {
      zoom: 1,
      coordinates: [0, 0]
    };

    _Class.prototype.zoomIn = function(zoomIncrease) {
      return this.set('zoom', this.get('zoom') * zoomIncrease);
    };

    return _Class;

  })(Backbone.Model);

  window.TargetFractalView = (function(_super) {
    __extends(_Class, _super);

    _Class.prototype.template = _.template("<div id='target-canvas'> <%= fractal %> <div id='target-zoom' class='zoom'><%= zoom %>x</div> </div>");

    function _Class(options) {
      if (options == null) {
        options = {};
      }
      this.render = __bind(this.render, this);
      this.model = options.model, this.classname = options.classname;
      $(document).on("ready", (function(_this) {
        return function() {
          _this.$el = $('#target-fractal');
          return _this.render();
        };
      })(this));
    }

    _Class.prototype.initialize = function() {
      return this.model.on('change', this.render, this);
    };

    _Class.prototype.render_fractal = function() {
      return 'dud';
    };

    _Class.prototype.render = function() {
      return this.$el.html(this.template({
        'zoom': this.model.get('zoom'),
        'fractal': this.render_fractal()
      }));
    };

    return _Class;

  })(Backbone.View);

}).call(this);
