// Generated by CoffeeScript 1.8.0
(function() {
  var target,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.TargetFractal = (function(_super) {
    __extends(_Class, _super);

    function _Class(zoom, coordinates) {
      this.zoom = zoom;
      this.coordinates = coordinates;
    }

    _Class.prototype.zoomIn = function(zoomIncrease) {
      return this.zoom = this.zoom * zoomIncrease;
    };

    return _Class;

  })(Backbone.Model);

  target = new window.TargetFractal();

}).call(this);
